name: maintenance
description: A Ms Flutter Firebase.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_storage:
  flutter_lints:
  cloud_firestore:
  firebase_auth:
  cupertino_icons:
  shared_preferences:
  flutter_svg:
  google_maps_flutter:
  carousel_slider:
  image_picker:
  uuid:
  flutter_local_notifications:
  firebase_messaging:
  timeago:
  flutter_html_to_pdf:
  path_provider:
  syncfusion_flutter_pdfviewer:

  #  google_sign_in: "^4.5.1"
  #  sign_in_with_apple: ^2.5.2
  #  crypto: ^2.1.5
  #  flutter_braintree: ^1.2.1
  #  flutter_twitter_login:
  #    git:
  #      url: https://github.com/Kiruel/flutter_twitter_login


  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/languages/
    - assets/images/
    - assets/images/icons/


  fonts:
    - family: NeoSansArabic
      fonts:
        - asset: assets/fonts/NeoSansArabic.ttf
