// M.s

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ignore: avoid_classes_with_only_static_members
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCvt0YUBZkfOTFStMwDE9V0BD-CLlSSqAQ",
    authDomain: "msplatform-6c94d.firebaseapp.com",
    projectId: "msplatform-6c94d",
    storageBucket: "msplatform-6c94d.appspot.com",
    messagingSenderId: "534485265386",
    appId: "1:534485265386:front:b477e6584445bc10d8e093",
    measurementId: "G-RDLRBZ1F18",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCvt0YUBZkfOTFStMwDE9V0BD-CLlSSqAQ",
    authDomain: "msplatform-6c94d.firebaseapp.com",
    projectId: "msplatform-6c94d",
    storageBucket: "msplatform-6c94d.appspot.com",
    messagingSenderId: "534485265386",
    appId: "1:534485265386:front:b477e6584445bc10d8e093",
    measurementId: "G-RDLRBZ1F18",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBS8xuAAHBxL4qZlnEn88U5-yD7fy4otDM",
    authDomain: "msplatform-6c94d.firebaseapp.com",
    projectId: "msplatform-6c94d",
    storageBucket: "msplatform-6c94d.appspot.com",
    messagingSenderId: "534485265386",
    appId: "1:534485265386:ios:37851df7fb1b32c8d8e093",
    measurementId: "G-RDLRBZ1F18",
    androidClientId:
    '534485265386-5aat8jafrcd6hgqmkkue7nn3f1hqtudt.apps.googleusercontent.com',
    iosClientId:
    '534485265386-5aat8jafrcd6hgqmkkue7nn3f1hqtudt.apps.googleusercontent.com',
    iosBundleId: 'com.omni.elive.omni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyCvt0YUBZkfOTFStMwDE9V0BD-CLlSSqAQ",
    authDomain: "msplatform-6c94d.firebaseapp.com",
    projectId: "msplatform-6c94d",
    storageBucket: "msplatform-6c94d.appspot.com",
    messagingSenderId: "534485265386",
    appId: "1:534485265386:front:b477e6584445bc10d8e093",
    measurementId: "G-RDLRBZ1F18",
    androidClientId:
    '785184947614-jvcu7agpj6n6vvr5poal14otu8mjdl61.apps.googleusercontent.com',
    iosClientId:
    '785184947614-70ii5qm94fe28nmasjc9g864nh25l4m7.apps.googleusercontent.com',
    iosBundleId: 'io.github.x-wei.flutter-catalog',
  );
}
